[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo"
  publish = "public"

[context.branch-deploy]
  command = "hugo"
  publish = "public"
